galaxy_info:
  description: Installs basic os-hardening such as disabling password for SSH
  author: kriansa
  license: Apache
  min_ansible_version: "2.11"

  platforms:
    - name: EL
      versions:
        - "10"
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - linuxhardening
    - osprimitives

dependencies: []
