galaxy_info:
  description: Install the latest version of Podman
  author: kriansa
  license: Apache
  min_ansible_version: "2.11"

  platforms:
    - name: EL
      versions:
        - "10"
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - containers

dependencies: []
