---
- name: Add /usr/local/bin to PATH for root users
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/root-local-bin.sh
    mode: "0644"
    content: |
      # Adds /usr/local/bin to $PATH for root
      [ -z "$EUID" ] && [ -x /usr/bin/id ] && EUID=$(/usr/bin/id -u)
      [ "$EUID" = "0" ] && PATH=${PATH/\/usr\/local\/sbin:/\/usr\/local\/sbin:\/usr\/local\/bin:}

- name: Create .config path for root user
  become: true
  ansible.builtin.file:
    path: /root/.config
    state: directory
    mode: "0700"
