---
# Cron is replaced by systemd timer units
- name: Remove anacron
  become: true
  ansible.builtin.dnf:
    state: absent
    autoremove: true
    name:
      - anacron
      - cronie
      - crontabs

- name: Remove cron folders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/anacrontab
    - /etc/crontab
    - /etc/cron.d
    - /etc/cron.hourly
    - /etc/cron.daily
    - /etc/cron.weekly
    - /etc/cron.monthly
    - /etc/cron.yearly

# Chrony (NTP timesync) is replaced by systemd-timesyncd
- name: Remove chrony
  become: true
  ansible.builtin.dnf:
    name: chrony
    state: absent
    autoremove: true

- name: Install systemd-timesyncd
  become: true
  ansible.builtin.dnf:
    name: systemd-timesyncd
    state: present

- name: Enable and start systemd-timesyncd
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started

- name: Remove chrony user
  become: true
  ansible.builtin.user:
    name: chrony
    state: absent

- name: Remove chrony group
  become: true
  ansible.builtin.group:
    name: chrony
    state: absent

- name: Remove old logs
  become: true
  ansible.builtin.file:
    path: /var/log/{{ item }}
    state: absent
  loop:
    - cron
    - chrony
